const express = require('express');
const mongodb = require('mongodb');
require('dotenv').config();

const router = express.Router();

// Fetch Data
router.get('/', async (req, res) => {

    const articles = await loadDatabaseCollections();
    res.send(await articles.find({}).toArray());
});

// Add Data
router.post('/', async (req, res) => {
    
    const articles = await loadDatabaseCollections();
    await articles.insertOne({
    title: req.body.title,
    image: req.body.image,
    imageCaption: req.body.imageCaption,
    category: req.body.category,
    author: req.body.author,
    date: req.body.date,
    content: req.body.content
    });

    // Confirmation of Resolution
    res.status(201).send();
});

// Delete Data
router.delete('/:id', async (req, res) => {

    const articles = await loadDatabaseCollections();

    // Takes unique article '_id' generated by mongodb and deletes respective entry from db
    await articles.deleteOne({ _id: new mongodb.ObjectID(req.params.id) });

    // Confirmation of Resolution
    res.status(200).send({});
});

async function loadDatabaseCollections() {

    const client = await mongodb.MongoClient.connect(
        process.env.API_KEY, { useNewUrlParser: true }
    );

    return client.db('pressapp').collection('posts');

}

module.exports = router;